import argparse
import subprocess
import os

def run_command(command, description):
    """
    Executes a shell command and checks for errors.
    """
    print(f"--- Executing: {description} ---")
    print(f"Command: {command}")
    try:
        subprocess.run(command, shell=True, check=True, executable='/bin/bash')
        print(f"--- {description} completed ---")
    except subprocess.CalledProcessError as e:
        print(f"--- Error: {description} failed! ---")
        print(f"Command '{e.cmd}' returned non-zero exit status {e.returncode}.")
        exit(1) # Exit script if command fails

def main():
    parser = argparse.ArgumentParser(description="Automated script for allele expression analysis.")
    parser.add_argument("--in_bam_list", required=True, help="Path to the list file containing BAM file paths.")
    parser.add_argument("--trans_vcf_script", required=True, help="Path to the trans_vcf.py script.")
    parser.add_argument("--vcf", required=True, help="Input VCF file (e.g., T1.snp2ase.vcf.gz).")
    parser.add_argument("--gtf", required=True, help="Path to the GTF file (e.g., region.gtf).")
    parser.add_argument("--phaser_script", required=True, help="Path to the phaser.py script.")
    parser.add_argument("--phaser_gene_ae_script", required=True, help="Path to the phaser_gene_ae.py script.")
    parser.add_argument("--out_prefix", required=True, help="Prefix for output files (e.g., T1).")
    parser.add_argument("--output_dir", default="test_result/04.allele_expression",
                        help="Directory where all output files will be saved (default: test_result/04.allele_expression).")

    args = parser.parse_args()

    # Get paths and prefix from arguments
    in_bam_list = args.in_bam_list
    trans_vcf_script = args.trans_vcf_script
    input_vcf = args.vcf
    gtf_file = args.gtf
    phaser_script = args.phaser_script
    phaser_gene_ae_script = args.phaser_gene_ae_script
    out_prefix = args.out_prefix
    output_dir = args.output_dir

    # Create the output directory if it doesn't exist
    os.makedirs(output_dir, exist_ok=True)
    print(f"--- Ensuring output directory '{output_dir}' exists ---")

    # Define paths for all output files, ensuring they are within the specified output_dir
    transformed_vcf = os.path.join(output_dir, f"{out_prefix}.info.snp.het.vcf.gz")
    gene_exon_bed = os.path.join(output_dir, "gene.exon.bed")
    # Note: vcftools --out creates a file name like <prefix>.recode.vcf directly in the output directory specified.
    # We construct the full path for subsequent bcftools command.
    temp_exon_vcf = os.path.join(output_dir, f"{out_prefix}.het.snp.exon.recode.vcf")
    final_exon_vcf = os.path.join(output_dir, f"{out_prefix}.het.exon.vcf.gz")
    region_bed = os.path.join(output_dir, "region.bed")
    
    # Phaser's output prefix for the --o argument
    phaser_output_prefix = os.path.join(output_dir, out_prefix)
    # The haplotypic counts file generated by phaser.py
    phaser_haplotypic_counts = f"{phaser_output_prefix}.haplotypic_counts.txt"
    # The final gene allele expression output file
    gene_ae_output = os.path.join(output_dir, f"{out_prefix}.gene_ae.txt")


    print("--- Starting allele expression analysis pipeline ---")

    # Step 1: Convert VCF file using trans_vcf.py
    run_command(
        f"python {trans_vcf_script} --invcf {input_vcf} --outvcf {transformed_vcf}",
        "VCF file format conversion"
    )

    # Step 2: Extract exonic regions from VCF based on GTF file
    print("\n--- Extracting exonic regions from VCF file ---")
    run_command(
        f"awk '($3==\"exon\") {{OFS=\"\\t\"; print $1,$4-1,$5}}' {gtf_file} > {gene_exon_bed}",
        "Extracting exon regions from GTF to BED file"
    )
    run_command(
        f"vcftools --gzvcf {transformed_vcf} --bed {gene_exon_bed} --recode --out {os.path.join(output_dir, f'{out_prefix}.het.snp.exon')}",
        "Filtering VCF file for exonic SNPs using VCFtools"
    )
    run_command(
        f"bcftools view -O z {temp_exon_vcf} > {final_exon_vcf}",
        "Reformatting VCF to compressed VCF"
    )
    run_command(
        f"bcftools index -t {final_exon_vcf}",
        "Creating index for the final VCF file"
    )

    # Step 3: Perform analysis using phaser.py and phaser_gene_ae.py
    print("\n--- Performing analysis with phaser ---")
    with open(in_bam_list, 'r') as f:
        bam_files = [line.strip() for line in f if line.strip()]

    if not bam_files:
        print("Error: BAM list file is empty or does not contain any valid BAM file paths.")
        exit(1)

    # Join all BAM file paths with a comma for phaser.py --bam argument
    joined_bam_paths = ",".join(bam_files)

    # Prepare region.bed file for phaser_gene_ae.py (generated only once)
    run_command(
        f"awk '$3==\"gene\"' {gtf_file} | cut -f 1,4,5,9 | cut -f 1 -d ';' | awk -F $'\\t' 'BEGIN {{OFS = FS}} {{split($4, a, \" \") ; print $1, $2-1, $3, a[2]}}' | sed 's/\"//g' > {region_bed}",
        "Extracting gene regions from GTF to BED file"
    )

    # Run phaser.py with the comma-separated list of BAM files
    print(f"\n--- Running phaser.py with multiple BAM files ---")
    run_command(
        f"python3 {phaser_script} --vcf {final_exon_vcf} --bam {joined_bam_paths} --paired_end 1 --mapq 60 --baseq 10 --sample ASE --o {phaser_output_prefix} --id_separator -",
        "Running phaser.py for all BAM files"
    )

    # Run phaser_gene_ae.py using the single haplotypic_counts file from phaser.py
    print(f"\n--- Running phaser_gene_ae.py ---")
    run_command(
        f"python {phaser_gene_ae_script} --haplotypic_counts {phaser_haplotypic_counts} --features {region_bed} --id_separator - --o {gene_ae_output}",
        "Analyzing gene allele expression using phaser_gene_ae.py"
    )

    print("\n--- All steps completed! ---")

if __name__ == "__main__":
    main()
